# Generated by Django 3.2.4 on 2021-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_controlvote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlvote',
            name='total_vote',
            field=models.IntegerField(default=0),
        ),
    ]
